plugin.id=WelcomeGreeting
plugin.version=1.0.0
plugin.class=com.example.plugin.samples.WelcomePlugin
plugin.provider=pbr
plugin.name=Greeting-Welcome
plugin.description=demo plugin for greeting
plugin.dependencies=